### ISSUE TITLE
Missing delete feature

### ISSUE THREAD

**Issue by binhonglee** [binhonglee/LibrarySystem#1]

**Comment by mwiggins09** [comment]
What kind of delete feature are you missing? I see a delete feature for both user and book.

**Comment by mwiggins09** [comment]
What kind of delete feature are you missing? I see a delete feature for both user and book.

**Comment by binhonglee** [comment]
@mwiggins09, Seems like my memory failed me. I forgot that I implemented it a little later after creating the first release. Thanks for the heads up!
